### PR TITLE
Fix java 20 support

### PR DESCRIPTION
**Pull request by rafi67000**
bump jdependency version to 2.9.0 (ASM related)

### CODE REVIEW

**Review by NotMyFault — APPROVED** [review]
Thanks, that's much needed for Java 20 support.

Could we get a release including this change please, @johnrengelman ?

**Review by rfresh2 — APPROVED** [review]
LGTM. Tested and fixes minimize task on JDK21

**Comment by Goooler** [comment]
Ones who need this can try my fork, see https://github.com/johnrengelman/shadow/pull/876#issuecomment-1783983216.

**Review by yannicklamprecht — APPROVED** [review]

**Comment by Nek-12** [comment]
When will this be merged?

**Comment by Goooler** [comment]
Closing due to #876.

**Pull request closed without merging**
